_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 5
                - 7
                - 35
                - 53
                - 55
                - 89
                - 105
            "2":
                - 5
                - 7
                - 35
                - 53
                - 55
                - 89
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.4
            "8":
                - 3
                - 8
            "12": 0.19.4
            "13": windows-amd64
model_name:
    value: catboost
n_trials:
    value: 50
run_id:
    value: "1"
