_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
epochs:
    value: 10
learning_rate:
    value: 0.02
model_type:
    value: RandomForestClassifier
