_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
activation:
    value: ReLU
dropout:
    value: 0.5
hidden_layer_sizes:
    value:
        - 32
        - 64
kernel_sizes:
    value:
        - 3
num_classes:
    value: 10
pool_sizes:
    value:
        - 2
