name: Deploy to Nebius VM
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.NEBIUS_SSH_KEY }}" ] || \
             [ -z "${{ secrets.NEBIUS_SSH_USER }}" ] || \
             [ -z "${{ secrets.NEBIUS_VM_HOST }}" ]; then
            echo "Missing required secrets"
            exit 1
          fi
          
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.NEBIUS_SSH_KEY }}

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.NEBIUS_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Sync All Files to Nebius VM
        run: |
          echo "Syncing all files to the VM..."
          rsync -avz --delete -e "ssh" ./ ${{ secrets.NEBIUS_SSH_USER }}@${{ secrets.NEBIUS_VM_HOST }}:/usr/src/project/
          
          ssh ${{ secrets.NEBIUS_SSH_USER }}@${{ secrets.NEBIUS_VM_HOST }} << 'EOF'
          sudo chown -R ${{ secrets.NEBIUS_SSH_USER }}:${{ secrets.NEBIUS_SSH_USER }} /usr/src/project
          sudo chmod -R 755 /usr/src
          EOF
