name: Deploy to Nebius VM
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.NEBIUS_SSH_KEY }}" ] || \
             [ -z "${{ secrets.NEBIUS_SSH_USER }}" ] || \
             [ -z "${{ secrets.NEBIUS_VM_HOST }}" ]; then
            echo "Missing required secrets"
            exit 1
          fi

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.NEBIUS_SSH_KEY }}

      - name: Sync Code to Nebius VM
        run: |
          rsync -e "ssh" ./preprocess.py ${{ secrets.NEBIUS_SSH_USER }}@${{ secrets.NEBIUS_VM_HOST }}:/tmp/
          
          ssh ${{ secrets.NEBIUS_SSH_USER }}@${{ secrets.NEBIUS_VM_HOST }} << 'EOF'
          sudo mv /tmp/preprocess.py /usr/src/preprocess.py
          sudo chown ${{ secrets.NEBIUS_SSH_USER }}:${{ secrets.NEBIUS_SSH_USER }} /usr/src/preprocess.py
          sudo chmod 755 /usr/src/preprocess.py
          EOF
